# PyTorch in One Hour: From Tensors to Training Neural Networks on Multiple GPUs
This notebook provides a quick introduction to PyTorch, covering the basics of tensors, operations, and training neural networks.
It is designed for those who want to get started with PyTorch quickly, focusing on practical examples and hands-on exercises.
It also includes examples of using multiple GPUs for training.

[Course Website](https://sebastianraschka.com/teaching/pytorch-1h/)


## What is PyTorch?
PyTorch is an open-source machine learning library developed by Facebook's AI Research lab. It provides a flexible and efficient platform for building and training deep learning models. PyTorch is known for its dynamic computation graph, which allows for more intuitive model building and debugging compared to static graph frameworks like TensorFlow.

### 3 Core Components of PyTorch

1. **Tensor Library**
   - PyTorch builds on NumPy with support for GPU acceleration
   - Allows seamless switching between CPU and GPU for high-performance computation

2. **Autograd Engine**
   - PyTorch includes automatic differentiation (autograd)
   - Simplifies backpropagation by automatically computing gradients during model training

3. **Deep Learning Framework**
   - PyTorch provides high-level utilities like pre-trained models
   - Includes loss functions and optimizers
   - Enables flexible and efficient development of deep learning models

These components make PyTorch powerful for both researchers and developers, balancing low-level control with high-level abstractions.

![PyTorch 3 Core Components](figures/pytorch_overview_3_pillars.jpg)



### 4 Defining Deep Learning
**Deep learning** is a subcategory of **machine learning** that is focused on the implementation of deep neural networks.
In turn, **machine learning** is a subcategory of **AI* that is concerned with algorithms that learn from data. **AI** is the broader concept of machines being able to perform tasks that typically require human intelligence.

![Deep Learning](figures/deep_learning.jpg)

Unlike traditional machine learning techniques that excel at simple pattern recognition, deep learning is particularly good at handling unstructured data like images, audio, or text, so deep learning is particularly well suited for LLMs.

Using a learning algorithm, a model is trained on a training dataset consisting of examples and corresponding labels. In the case of an email spam classifier, for example, the training dataset consists of emails and their spam and not-spam labels that a human identified. Then, the trained model can be used on new observations (new emails) to predict their unknown label (spam or not spam).

Of course, we also want to add a model evaluation between the training and inference stages to ensure that the model satisfies our performance criteria before using it in a real-world application.

![Supervised Modeling Workflow](figures/predictive_modelling_workflow.jpeg)

The workflow in Figure above also applies to LLMs—whether for text classification or generation. For generation tasks, labels during pretraining are derived from the text itself, and the model produces new text based on an input prompt during inference.





### 4 Understanding Tensors
**Tensors** are the fundamental data structure in PyTorch, similar to NumPy arrays but with additional capabilities for GPU acceleration. Tensors can be one-dimensional (vectors), two-dimensional (matrices), or multidimensional (n-dimensional arrays). They are used to represent data in deep learning models and can be manipulated using various operations.

![Deep Learning](figures/tensors.jpeg)

PyTorch tensors are similar to NumPy arrays but have several additional features important for deep learning. For example, PyTorch adds an automatic differentiation engine, simplifying computing gradients. PyTorch tensors also support GPU computations to speed up deep neural network training.



### 5 Scalars, Vectors, Matrices, and Tensors
- **Scalars**: Single numerical values (0D tensors).
- **Vectors**: One-dimensional arrays (1D tensors).
- **Matrices**: Two-dimensional arrays (2D tensors).
- **Tensors**: Multi-dimensional arrays (nD tensors).


In [4]:
import torch

# Create a scalar tensor
scalar_tensor = torch.tensor(5.0)
print("Scalar Tensor:", scalar_tensor)

# Create a vector tensor
vector_tensor = torch.tensor([1.0, 2.0, 3.0])
print("Vector Tensor:", vector_tensor)

# Create a matrix tensor
matrix_tensor = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print("Matrix Tensor:\n", matrix_tensor)

# Create a 3D tensor
three_d_tensor = torch.tensor([[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]])
print("3D Tensor:\n", three_d_tensor)


Scalar Tensor: tensor(5.)
Vector Tensor: tensor([1., 2., 3.])
Matrix Tensor:
 tensor([[1., 2.],
        [3., 4.]])
3D Tensor:
 tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [3]:
# check if my Mac supports PyTorch acceleration with its Apple Silicon chip
import torch
print(torch.backends.mps.is_available())

True


### 6 Common PyTorch Tensor Operations
- **Creation**: Create tensors from lists, NumPy arrays, or random values.
- **Reshaping**: Change the shape of tensors without changing their data.
- **Indexing and Slicing**: Access specific elements or sub-tensors.
- **Arithmetic Operations**: Perform element-wise operations like addition, subtraction, multiplication, and division
- **Matrix Operations**: Perform matrix multiplication and other linear algebra operations.
- **Broadcasting**: Automatically expand tensors to compatible shapes for operations.
- **Concatenation**: Combine tensors along a specified dimension.
- **Stacking**: Combine multiple tensors into a new tensor along a new dimension.
- **Splitting**: Divide a tensor into smaller tensors along a specified dimension.
- **Cloning**: Create a copy of a tensor to avoid modifying the original tensor.
- **Transposing**: Swap dimensions of a tensor to change its shape.
- **Permuting**: Rearrange dimensions of a tensor to change its order.
- **Resizing**: Change the size of a tensor while preserving its data.
- **Type Conversion**: Convert tensors between different data types (e.g., float to int).
- **Device Management**: Move tensors between CPU and GPU for efficient computation.
- **Memory Management**: Manage tensor memory allocation and deallocation.
- **Gradient Tracking**: Enable or disable gradient tracking for tensors to control autograd behavior.
- **In-place Operations**: Perform operations that modify the tensor in place to save memory.
- **View Operations**: Create a new view of a tensor with a different shape without copying data.
- **Clamping**: Limit tensor values to a specified range.
- **Normalization**: Scale tensor values to a specific range or distribution.
- **Masking**: Create boolean masks to filter tensor elements based on conditions.
- **Sorting**: Sort tensor elements along a specified dimension.
- **Unique Elements**: Find unique elements in a tensor.
- **Element-wise Comparison**: Compare tensor elements to create boolean tensors.
- **Reduction Operations**: Compute summary statistics like sum, mean, max, and min across dimensions.
- **Logical Operations**: Perform logical operations like AND, OR, and NOT on tensors.
- **Element-wise Functions**: Apply functions like square root, exponential, and logarithm to tensor elements.


In [6]:
#creation
import torch

# Create a tensor from a list
tensor_from_list = torch.tensor([1.0, 2.0, 3.0])
print("Tensor from list:", tensor_from_list)
# Create a tensor from a NumPy array
import numpy as np
numpy_array = np.array([[1.0, 2.0], [3.0, 4.0]])
tensor_from_numpy = torch.tensor(numpy_array)
print("Tensor from NumPy array:\n", tensor_from_numpy)
# Create a random tensor
random_tensor = torch.rand(2, 3)  # 2x3 tensor with random values
print("Random Tensor:\n", random_tensor)
# Create a tensor filled with zeros
zero_tensor = torch.zeros(2, 3)  # 2x3 tensor filled with 0s
print("Zero Tensor:\n", zero_tensor)
# Create a tensor filled with ones
ones_tensor = torch.ones(2, 3)  # 2x3 tensor filled with 1s
print("Ones Tensor:\n", ones_tensor)
# Create a tensor with a specific data type
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
print("Float Tensor:", float_tensor)
# Create a tensor with a specific device (CPU or GPU)
device_tensor = torch.tensor([1.0, 2.0, 3.0], device='cuda' if torch.cuda.is_available() else 'cpu')
print("Device Tensor:", device_tensor)


Tensor from list: tensor([1., 2., 3.])
Tensor from NumPy array:
 tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
Random Tensor:
 tensor([[0.5182, 0.8637, 0.6504],
        [0.4657, 0.7124, 0.7179]])
Zero Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Float Tensor: tensor([1., 2., 3.])
Device Tensor: tensor([1., 2., 3.])


### 6 Seeing models as computation graphs
![Computation Graph](figures/computation_graph.jpg)
